### ISSUE TITLE
Initial Installation

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#1]
### Acceptance Criteria:
- [x] Install all libraries and other programs required.
- [x] Create env.py file and hide all sensitive information. 

### Tasks:
- [ ] Install : django, dj-database, psycopg2, gunicorn, cloudinary
- [x] Create env.py file
- [x] Hide django secret key in env.py file
