### ISSUE TITLE
Creating the home page view and accessing posts.

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#10]
As a **visitor** I can **view a list of posts on the home page** so that **I can select which post I want to view.**

### Acceptance Criteria:
- [x] User can access the home page with a paginated list of posts to select.
- [x] When a user opens the main page a list of posts is seen.
- [x] Given more than one post in the database, these multiple posts are listed.
- [x] Then the user sees all post titles with pagination to choose what to read.

### Tasks:
- [x] Create homepage view and URL path.
- [x] In views.py create generic list view to add post list to home page.
- [x] Add filters and attributes to queryset to filter for only approved posts, and order the posts newest to oldest.
