### ISSUE TITLE
Add Django Summernote

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#11]
As a **developer** I can **access Django Summernote on the admin panel** so that **more easily add blog posts with access to features on Summernote.**

### Acceptance Criteria:
- [x] Site admin users can create posts on the admin panel using features on Django Summernote.
- [x] Site admin users can more easily create, read, update and delete their posts using the Summernote text editor.

### Tasks:
- [x] Download Django Summernote package.
- [x] Add to requirements file.
- [x] Add to installed apps.
- [x] Add url path to goodnews/urls.py.
- [x] Import summernote on blog/admin.py.
- [x] Create summernote class in admin.py and register post model.
