### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#12]
As a **visitor** I can **sign up** so that **I can access features for registered users.**

### Acceptance Criteria:
- [x] a user should be able to create account with username and password.
- [x] user credentials should be fully validated and secure, and saved to the database.
- [x] User should be able to sign up by clicking on the relevant link in the navigation bar.

### Tasks:
- [x] Add sign up model.
- [x] Create html template for sign up form.
- [x] Create link to sign up url in base template navigation.
- [x] Add link to SIGN IN page if user already has an account.
- [x] Create all relevant code for validating user.
- [x] Run the server and test functionality.
- [x] Deploy and test deployed version.
