### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#13]
As a **registered user** I can **log into website using my registered credentials** so that **access all features on the site.**

### Acceptance Criteria:
- [x] The user should be able to login.
- [x] A user can access the link to the login page on the navigation bar.
- [x] Login feature should verify user identity using their password and username. 
- [x] When logged in, the navigation should display "logged in as" + username alongside new "logout" button.

### Tasks:
- [x] Create login model
- [x] Create login html template and file.
- [x] Create login form.
- [x] Add link to login url to navigation.
- [x] Create "logged in as" + username text and log out button to replace log in/register buttons.
- [x] run server and test functionality.
- [x] deploy app and test functionality.
