### ISSUE TITLE
User Log out

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#14]
As a **registered user** I can **log out of my account** so that **exit my profile and keep my account safe.**

### Acceptance Criteria:
- [x] A user should be able to log out of their account.
- [x] A user should be asked if they are sure they want to log out and confirm their decision.
- [x] A user should be notified when they are logged out.
- [x] "logged in as" and "log out" button changed to buttons to register/log in.

### Tasks:
- [x] Create log out function.
- [x] Create "log out" button on navigation bar
- [x] Create confirmation alert for user to confirm they want to log out.
- [x] Run server and test functionality
- [x] Deploy and test functionality.
