### ISSUE TITLE
Accessing Blog Posts

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#15]
As a **user** I can **scroll through many different blog posts** so that **I can find relevant information that interests me and further interact with the site.**

### Acceptance Criteria:
- [x] A user can access all the blog posts on the list on the landing page.
- [x] A user sees the title, excerpt (description), and a featured image related to the article with a link to access the full article.
- [x] A user has a wide range of different posts they can read through.

### Tasks:
- [x] Create content for all blog posts, add all data to post_list.json.
- [x] Install Cloudinary for the featured images.
- [x] Create paginated list of all posts on the home screen with "prev" and "next" button. 
- [x] Run server and test all links and buttons functionality.
- [x] Deploy project and test all links and buttons functionality.
