### ISSUE TITLE
Style Header Nav and Footer using Bootstrap

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#16]
As a **developer** I can **use bootstrap and DTL to design and style the header and footer** so that **reuse the template on all html pages and save some time coding.**

### Acceptance Criteria:
- [x] User should be able to access the navigation and footer links on all html pages.
- [x] User should have a positive response to the design and layout of the header and footer and easily navigate through the links and other information.

### Tasks:
- [x] Download all meta data for bootstrap and fontawesome.
- [x] Use bootstrap to implement a basic design model structure. (Find in Readme.md)
- [x] Test all new links and buttons functionality on the local server.
- [x] Deploy to Heroku and test functionality.
