### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#19]
As a **developer** I can **access bootstrap and CSS** so that **I can style all the web pages and ensure a positive user experience.**

### Acceptance Criteria:
- [x] A user should be able to access all views with finished styling.
- [x] All users should be able to fully experience the site and find it easy and clear to read and interact with.
- [x] Users of all ages and abilities should be able to navigate the site easily.

### Tasks:
- [x] Ensure all colours and typography are within accessibility guidelines and are readable to all users.
- [x] Ensure alt attributes are correctly added where they need to be.
- [x] Ensure all images being used for design on the site are properly sized and compressed as needed.
- [x] Ensure site is responsive across all screen sizes, including text, photographs, letter spacing and sizing.
- [x] Deploy and test responsive functionality, links and media queries.
