### ISSUE TITLE
 Give administrator special credentials

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#2]
As a **site administrator** I can **have special credentials** so that **I can only access all information on the site.**

### Acceptance Criteria:
- [x] Administrator login information should be kept secret /hidden only to be accessed by site administrator(s).
- [x] Administrator should be able to access all information on the site.
- [x] Username and password for superuser should be unique.
- [x] To access this specific area administrator should login from the Login section

### Tasks:
- [x] Create superuser in the terminal
- [x] Update login section for superuser
- [x] Test Functionality
