### ISSUE TITLE
Create Contact App

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#20]
As a **user** I can **access the contact page** so that **I can get in contact with the site and ask any questions, or provide any feedback I might want.**

### Acceptance Criteria:
- [ ] Unregistered or logged in users can access the feedback/contact form on the contact page.
- [ ] Site admin should be able to access all feedback from the site admin panel.

### Tasks:
- [x] Create Contact app directory, view and URL path.
- [ ] Create contact form using DTL and crispy forms.
- [ ] Ensure form is wired to database correctly and site admin can access feedback within the database.
- [ ] Deploy and test functionality of form and database feedback.

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
