### ISSUE TITLE
BUG - link CSS file correctly for deployment.

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#21]
Can't find a way to link the style sheet and have the styles displayed on the deployed version as they are in the local server.

Update - FIXED

### Tasks:
- [x] Find a way to display CSS on deployed version.

### Could Try??
- [x] Changing the file path structure
- [x] Not including DTL tag in href 
- [x] Install whitenoise and delete collectstatic from config vars.
