### ISSUE TITLE
User Likes

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#22]
As a **logged in user,** I can **like different blog posts I find interesting** so that **I can share positivity on the website and show other users what posts to read.**

### Acceptance Criteria:
- [ ] A logged in user can like (react) to any blog post.
- [ ] A like symbol can be displayed with a clear heart symbol for an unliked post, and a filled heart symbol for a liked post. (image in Readme)
- [ ] A logged in user can dislike/unlike a liked post by re clicking on the heart symbol.
- [ ] A site administrator can access all likes data within the database.

### Tasks:
- [ ] Create like model within models.py
- [ ] Register model.
- [ ] Create like functionality on blog posts.
- [ ] Create like button and test functionality.
- [ ] deploy project and test all new functionality.

UPDATE: won't include this feature, add screenshot of issue to 'future features' readme.md section.
DON'T CLOSE this issue until all like models, views, urls and references are removed from project files.
