### ISSUE TITLE
View full blog posts

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#23]
As a **user** I can **access full blog posts from the blog post list on the home page** so that **read, like and comment on whatever blog post I would like.**

### Acceptance Criteria:
- [x] A user should be able to access any blog posts from their link in the list of post on the home page.
- [x] A user should be redirected to blog post page and be able to read all post content.

### Tasks:
- [x] Create all relevant views and file paths. 
- [x] Create add to post_detail.html page.
- [x] Test functionality on local server.
- [x] deploy and test all new functionality.
