### ISSUE TITLE
Enable User Authentication 

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#24]
As a **developer** I can **enable users to be authenticated using Django All Auth** so that **I can guarantee safe authentication across site platforms.**

### Acceptance Criteria:
- [x] Users can register securely.
- [x] Site administration can manage users securely.

### Tasks:
- [x] Install Django AllAuth.
- [x] Add new apps to installed apps in settings.py.
- [x] Add 'site id', 'login redirect url' and 'logout redirect url' constants to settings.py
- [x] Add allAuth to middleware in settings.py
- [x] Add account email verification constant with value of "none" as not using email verification for login. (MAYBE)
- [x] Migrate changes.
- [x] Add 'accounts' URL path to goodnews/urls.py.
- [x] Update base.html to include urls for login/logout/signup pages.
- [x] Add register/login links to navigation section in base.html and runserver to check if login pages have been added.
- [x] Copy the allauth template files to the projects templates directory and add content to files for all html pages.
- [x] Deploy and test functionality.
