### ISSUE TITLE
Create user app

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#26]
As a **user** I can **access my user page** so that **I can add a profile photo and manage my blog posts and profile information.**

### Acceptance Criteria:
- [x] Registered and logged in users can access their user profile page through clicking their username or user icon in the nav bar.
- [x] User can update their user image which can be displayed on any comments/blog posts they create. 
- [x] User can perform CRUD functionality on their posts/comments from accessing features on their user profile. (might not have)

### Tasks:
- [x] Create and install user profile app, wire up all file paths and links.
- [x] Install Cloudinary for user profile image.
- [x] Create User model - ERD.
- [x] Create user page html.
- [x] Create list of liked posts and comments (might not have).
