### ISSUE TITLE
BUG: contact app + django crispy

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#27]
Had issues with the contact app using django crispy - created bug that prevented me from running server. 

### current fix:
- Deleted contact app and all references to it throughout the project.
- Added feedback form to about page to create and test base functionality.

- [ ] Need to find a way to re create contact page step by step and try to add form.

### Tasks:
- [ ] create contact app ( again ) refer to issue #20 
- [ ] add crispy form from about page to contact page.
- [ ] test functionality on server and deployed page.
----------------------------------- 
### If that doesn't work:
- [ ] Figure out how to link contact tab in navigation to contact form on about page ( from all pages ). - Currently links from about page correctly but no other page. "#contact"
- [ ] style about page to include contact information from contact page as well as feedback form styles.
