### ISSUE TITLE
Create GoodNews project and blog app with django

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#3]
As a **developer** I can **create my first project and app directory** so that **I can return a HTTP response and test functionality.**

### Acceptance Criteria:
- [x] Create Goodnews Project directory.
- [x] Create app using django and the terminal.
- [x] Return a message in the terminal when server is running.

### Tasks:
- [x] Use startproject command to install project directory named "goodnews"
- [x] Use startapp command to create new app directory named "blog"
- [x] Add new app name to Installed apps variable in settings.py
- [x] In blog/views.py, import HttpResponse from django.http.
- [x] In blog/views.py, create view function that returns a http response with a test message.
- [x] In goodnews/urls.py, import the new blog views function.
- [x] In goodnews/urls.py, create new url path for the new blog view.
- [x] Run server, append "/blog" to url path to check if message has displayed.
