### ISSUE TITLE
README

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#30]
As a **developer** I can **document all project content in my readme.md file** so that **I can have all information on the site on record for me or other developers.**

### Acceptance Criteria:
- [ ] Readme.md file is complete with all relevant sections.
- [ ] Readers can access screenshots as well as written content for greater detail.

### Tasks:
- [ ] Complete writing all readme sections 
- [ ] Add screenshots for all feature sections and other relevant sections ie: agile, wireframes, colour scheme, data schema.
