### ISSUE TITLE
TESTING.md

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#31]
As a **developer** I can **document all automatic and manual testing in a testing.md file** so that **I can have a clear, detailed document of all testing for my own reference and for other developers.**

### Acceptance Criteria:
- [ ] Testing.md file should contain all testing information sections, as well as validation for all languages and lighthouse testing results.
- [ ] Testing.md file should contain screenshots with detailed text for all sections where possible.

### Tasks:
- [ ] Complete writing all documentation in testing.md section, including all testing results and explanations.
- [ ] Include screenshots to accompany documentation to ensure clear information presented.
