### ISSUE TITLE
Home Page - Styles

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#32]
As a **site user** I can **access the site's home page with elegant styling** so that **I can ensure a positive user experience when navigating the site.**

### Acceptance Criteria:
- [x] Users can access the home page with styles like the design layout wireframe.
- [x] Users can easily navigate through the home page with all information presented as clear and accessible.
- [x] Accessibility guidelines are met across all sections to ensure a positive user experience for all users.
- [x] Users can access the site information clearly on all screen sizes.

### Tasks:
**This includes:  base.html, index.html and post_detail.html**
- [x] Complete styling on navigation bar:
     - [x] Good News logo in the middle of page, with tabs on each side.
     - [x] Change typography for logo and tabs.
     - [x] Perhaps a different colour scheme?? (MIGHT NOT INCLUDE)
- [x] Add final img choice for landing banner, decide on a quote to feature.
- [x] Style article cards on display:
     - [x] Typography needs changing.
     - [x] Featured image to be the same size on all cards. (fix the bird img)
     - [x] Change font colours to match final colour theme.
     - [x] size for like and comment icons.
     - [x] Border radius on cards.... i hate them as they are.
 - [x] Style Footer:
     - [x] Social media icons need fixing - refer to design model wireframe.
     - [x] SOCIAL MEDIA ICONS NEED HREF. 
     - [x] Logo , position and size
     - [x] Contact information needs fixing.
