### ISSUE TITLE
About Page - Syles

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#33]
As a **site user** I can **access the site's about page with elegant styling** so that **I can ensure a positive user experience when navigating the site.**

### Acceptance Criteria:
- [x] Users can clearly access about page and all information.
- [x] Accessibility guidelines are met across all sections of about page, ensuring a positive user experience for all users.
- [x] Users can access good styling on all screen sizes.

### Tasks:
- [x] About section:
    - [x] About text: create a new about section and add to section.
    - [x] About text: Typography and font colour needs fixing.
    - [x] Add an image to about page.
- [x] Contact section: see #34 
- [x] Fix nav bug, see #29 
- [x] Ensure all images used have correct alt labels.
