### ISSUE TITLE
About Page: CONTACT SECTION - Styles

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#34]
As a **site user** I can **access the site's home page with elegant styling** so that **I can ensure a positive user experience when navigating the site.**

### Acceptance Criteria:
- [x] Users can clearly access the contact information and contact form.
- [x] Accessibility guidelines are met and ensuring all users to have a positive experience navigating the site information.
- [x] Contact information can be accessed by users clearly on all screen sizes.

### Tasks:
- [x] Add styles to contact form:
    - [x] Colour scheme and Typography.
    - [x] Clear letter spacing.
    - [x]  Input boxes are clear and easy to read.
- [x] Create banner space between about and contact sections.
