### ISSUE TITLE
Login/Logout/Register - Styles

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#35]
As a **site user** I can **access the site's login/logout/register page with elegant styling** so that **I can ensure a positive user experience when navigating the site.**

### Acceptance Criteria:
- [x] Users can clearly access the site's login/logout/register information to ensure a positive user experience to new and registered users.
- [x] Accessibility guidelines are met across all sections to ensure a good user experience for all users.
- [x] All forms are easy to read and see on all screen sizes.

### Tasks:
- [x] Add styles to all forms:
    - [x] Typography and colour scheme.
    - [x] input boxes and labels are clear and easy to read.
- [x] Login/logout notification needs styles.
- [x] ensure all buttons/ input tags are correctly aria-labelled.
