### ISSUE TITLE
Lighthouse Testing

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#36]
As a **developer** I can **generate a lighthouse test** so that **I can test page speed, accessibility, and SEO.**

### Acceptance Criteria:
- [ ] Lighthouse score for all site pages generated and can add any changes to improve result if needed.

### Tasks:
- [ ] Open Chrome dev tools and generate lighthouse result for all pages.
- [ ] Screenshot results to add to testing file.
