### ISSUE TITLE
W3 HTML Validator

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#37]
As a **developer** I can **test using W3 HTML Validator** so that **I can check and solve any html errors or issues throughout the project.**

### Acceptance Criteria:
- [x] Validator test results generated and can make any necessary changes to fix any present errors.

### Tasks:
- [x] Open W3 Website and validate html by direct input link, use heroku link.
- [x] validate each html page by using the source code of each page from the deployed link.
- [x] Fix any errors present.
- [x] Document any fixes and screenshot result when no errors are present.
