### ISSUE TITLE
JSHint Validation

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#38]
As a **developer** I can **use JSHint Validator to check for any errors in Javascript files** so that **solve any errors that could be present.**

### Acceptance Criteria:
- [x] JSHint results generated and any present errors can be fixed by a developer.

### Tasks:
- [x] Open JSHint website and copy and paste javascript files one by one.
- [x] Fix any errors listed.
- [x] Screenshot result once all errors are fixed.
