### ISSUE TITLE
PEP8 Python Validator

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#39]
As a **developer** I can **use PEP8 Python Validator to check for any errors in python files** so that **solve any errors that could be present.**

### Acceptance Criteria:
- [x] PEP8 results generated and any present errors can be fixed by a developer.

### Tasks:
- [x] Open PEP8 website and copy and paste Python files one by one.
- [x] Fix any errors listed.
- [x] Screenshot result once all errors are fixed.
