### ISSUE TITLE
Initial Deployment

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#4]
As a **developer** I can **manually deploy my site on heroku** so that **I can test functionality or features when deployed.**

### Tasks:
- [x] Create new app on Heroku dashboard.
- [x] Set config vars key and value.
- [x] Install gunicorn and add correct information to Procfile.
- [x] add '.heroku.com' to ALLOWED_HOSTS variable in settings.py.
- [x] Connect Github repository to new Heroku app.
- [x] Manually deploy site on Heroku deployment tab and append "/blog" to url path to find the test message.
