### ISSUE TITLE
Tidying Up 

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#40]
As a **developer** I can **carry out various tasks to tidy up my code** so that **I can maintain good industry practices and enable developers to greater read and understand my code.**

### Acceptance Criteria:
- [x] All python files have correct docstrings that are clear and easy to understand. 
- [ ] All code should be tidied and ready for final push and deployment for testing and submission.

### Tasks:
- [x] Add docstrings to all functions and class names in every file directory that contains python files. (refer to tidying up video in walkthrough for documentation)
- [x] Delete all commented out code.
- [x] Remove all print statements from functions. (Use search feature on VS code: search 'print')
- [x] Tidy up CSS file and maintain good structure with correct labels for different sections, media queries etc.
- [x] Make sure all file names and directory names are lowercase with no spaces.
- [ ] Make sure all image files are the correct name and SIZE.
- [ ] Ensure all IMPORTS are listed in files in their correct order.
- [ ] Ensure all Must Have User Stories (not Testing) have been completed and closed. All Should have stories or incomplete features are correctly labelled and in their correct place on the board.
