### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#41]
As a **developer** I can **enable error handling** so that **I can evade any crashes or bugs on the site.**

### Acceptance Criteria:
- [x] Error messages to be displayed to a user when the site encounters any server errors.

### Tasks:
- [x] Create error handler in views and models
- [x] Create error page to be displayed to user
- [x] Test functionality
