### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#42]
As a **developer** I can **use a favicon icon for my browser tab** so that **I can enhance the user experience and the branding/theme of site.**

### Acceptance Criteria:
- [x] Logo will be featured and easy to see on the browser tab when deployed.

### Tasks:
- [x] Generate favicon
- [x] Add to html structure on base html head
- [x] deploy and test functionality.
