### ISSUE TITLE
BUG: text field for user posts - responsive design

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#44]
Currently using django summernote text editor on the user profile page on the section for users to create their own blog posts, text editor creates a push that all the content has a large gap to the right. 

Currently:
I have done a makeshift adjustment to the bootstrap classes to enable users with larger screens to access the text editor - There is still a slight push to the right on mobile screen sizes without the text editor. 

### Acceptance Criteria:
- [x] Only users with 1200 px **(edit: decided 1450px was better to include laptop/desktop users for this feature only)** screen size can access the text editor, so including laptops, large tablets on landscape mode, and desktops. 
- [x] Users using a mobile phone or a small/medium tablet can access their profile as usual, but instead of the 'add post' section there is a message letting them know they must log on using a computer if they wish to add their own post.

### Tasks:
- [x] Add sections to user profile html file to include for users of different screen sizes.
- [x] Add media queries to css file to enable users of specific screen sizes to view each section : ( flex, display, block)
- [x] Find a way to fix the push on the mobile screen size, adjust bootstrap classes on user information section. (if cannot fix then add to bugs section of readme/features)
