### ISSUE TITLE
User Profile - styles

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#46]
As a **registered user** I can **access my profile page with elegant styling** so that **I can ensure a positive user experience when navigating the site, and I can easily access all the features on the user profile.**

### Acceptance Criteria:
- [x] Registered user can access their profile page and easily navigate through the features available.
- [x] All information for features is clearly and appropriately styled ensuring readability and accessibility guidelines are met.

### Tasks:
**This includes: user_profile.html, profile_update.html and profile_delete.html.**
- [x] User information section needs to be properly adjusted: , 
    - [x] colours added
    - [x] hover styles on buttons
    - [x] good spacing on the screen on all screen sizes
    - [x] profile picture is a decent size and user information is clear and easy to read.
    - [x] add alt tag to image tag if needed.
    
- [x] Post list needs to look MUCH better than it does:
    - [x] Ensure information is clear and well spaced.
    - [x] maybe add a box section around it and change the colour for readability.
    - [x] delete button on post list items needs to look a bit cuter 
    - [x] ensure section has a clear title.
     
- [x] Add post section needs MUCH work:
    - [x] form needs to be styled.
    - [x] clear paragraph explaining each form input.. figure out a way to label them better.
    - [x] change colours and font.
