### ISSUE TITLE
Automated Testing

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#48]
As a **developer** I can **carry out automated testing tasks** so that **quickly and thoroughly test all views, models and forms on my site.**

### Acceptance Criteria:
- [x] All automated testing functions are easy to find within their appropriate folders, ie: test_forms.py, test_views.py and test_models.py.
- [x] Running test command in terminal generates results of all test functions.

### Tasks:
- [x] Create testing files and define testing functions within the test classes.
