### ISSUE TITLE
Creating a database

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#5]
As a **developer** I can **create the database** so that **I can access full CRUD functionality for any data on the site.**

### Tasks:
- [x] Create postgres instance using Code Institute link.
- [x] Create env.py file and add to gitignore file.
- [x] Within env.py, import os.
- [x] Within env.py, set default settings of environment variable and include the postgres link that was sent. 
- [x] Install DJ Database and psycopg2 and add them to requirements.txt file
- [x] Within goodnews/settings.py, import os, import dj_database_url and import env.
- [x] Comment out SQL database variable code in settings.py and replace with new code to assign database variable to postgres link we just added to env.py.
- [x] migrate changes made.
- [x] add database url to config vars.
- [x] Create secret key and add to env.py and config vars on heroku before deployment.
