### ISSUE TITLE
Creating About App

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#7]
As a **visitor** I can **access the about page** so that **find out more information about the site, and maybe provide feedback.**

### Acceptance Criteria:
- [x] The user can access an about page through the navigation link.
- [x] Users can read about the website through the about content.
- [x] Site admin can access about content from admin panel and edit the content as they see fit.

### Tasks:
- [x] Create about app directory.
- [x] Create about page view and url path.
- [x] Create about model.
- [x] Create template directory and add about.html file.
- [x] Add about content to give users more information on the website.
