### ISSUE TITLE
Create base, blog and about HTML templates

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#8]
As a **developer** I can **create different html templates using DTL** so that **save time coding html and create greater efficiency.**

### Acceptance Criteria:
- [x] Views for home page, blog posts and about page can be displayed to user.
- [x] Basic style and structure for content, navigation and footer.

### Tasks:
- [x] Create directories for templates in all relevant app directories and create html files.
- [x] Add views and url paths for all new html files.
- [x] Within base html, create all html for header, main and footer sections.
- [x] Within blog html and about html pages, add basic semantic structure for features to be added.
- [x] Wire up links to pages in the relevant navigation links in navbar.
- [x] Run server and test functionality.
- [x] Manually deploy site on Heroku and test all added functionality.
