### ISSUE TITLE
Adding Comments (superuser)

### ISSUE THREAD

**Issue by FernVR** [FernVR/GoodNewsBlog#9]
As a **site administrator** I can **add and access all comments on the admin page** so that **maintain control over user interactions on the site.**

### Acceptance Criteria:
- [x] Superuser can access all comments through the admin page using the comment model on the database.
- [x] Superuser can create, read, update and delete all comments on the admin page.

### Tasks:
- [x] Create comment model in blog/models.py.
- [x] Make migrations and migrate new model.
- [x] Register comment model in admin.py.
